### PR TITLE
Add Ghidra docs.

### PR DESCRIPTION
**Pull request by Hornos3**
Added Ghidra docs parsed through pandoc. It may have improper parses in some html files that is needed to be optimized soon.

### CODE REVIEW

**Comment by tttturtle-russ** [comment]
Your commit contains an unnecessary file `.idea/.gitignore`. plz remove it.

**Comment by mudongliang** [comment]
1. You need to sign CLA;
2. You need to make CI happy if CI is correct;
3. I suggest you could firstly collect the core articles into our repo;

**Comment by Hornos3** [comment]
> 1. You need to sign CLA;
> 2. You need to make CI happy if CI is correct;
> 3. I suggest you could firstly collect the core articles into our repo;

The CI seems to fail in citing pics, I've observed some md files merged and see that pics in the same directory of md file can be cited, but mine has a "image/" and it cannot recognize it. If it's the problem of astro, plz tell me and I'll adjust the file structure and  make pics and mds in the same directory.

eg. 
-- example.md (cited images/somepic.png)
-- images
  |
  -- somepic.png
The astro will report an error in such an example above

**Comment by Hornos3** [comment]
@mudongliang

**Comment by mudongliang** [comment]
按照之前仓库的情况，相对地址的picture应该是没问题的，你看看是不是用了绝对地址？另外，建议你先只放少数核心文件（10-20篇左右）

**Comment by Hornos3** [comment]
@mudongliang 我看了那个报错，是相对的地址，不知道为什么就是不行

**Comment by Hornos3** [comment]
I've mistaken the global email address, so the licence check is always pending. I'll close this and create another one.

**Pull request closed without merging**
